-- 1. Run this file to create the target tables.
-- 2. In Snowsight, load data/ai4i2020.csv into OAD_DEMO.PUBLIC.AI4I_SOURCE.
--    Keep the CSV header and map columns in file order.
-- 3. Run snowflake/002_expand.sql to create the five-million-row workload.

CREATE DATABASE IF NOT EXISTS OAD_DEMO;
CREATE SCHEMA IF NOT EXISTS OAD_DEMO.PUBLIC;

CREATE TABLE IF NOT EXISTS OAD_DEMO.PUBLIC.AI4I_SOURCE (
    UDI NUMBER(10, 0),
    PRODUCT_ID VARCHAR(16),
    PRODUCT_TYPE VARCHAR(1),
    AIR_TEMPERATURE_K FLOAT,
    PROCESS_TEMPERATURE_K FLOAT,
    ROTATIONAL_SPEED_RPM NUMBER(10, 0),
    TORQUE_NM FLOAT,
    TOOL_WEAR_MIN NUMBER(10, 0),
    MACHINE_FAILURE NUMBER(1, 0),
    TWF NUMBER(1, 0),
    HDF NUMBER(1, 0),
    PWF NUMBER(1, 0),
    OSF NUMBER(1, 0),
    RNF NUMBER(1, 0)
);

CREATE OR REPLACE TABLE OAD_DEMO.PUBLIC.AI4I_READINGS (
    READING_ID NUMBER(38, 0),
    REPETITION_NUMBER NUMBER(10, 0),
    UDI NUMBER(10, 0),
    PRODUCT_ID VARCHAR(16),
    PRODUCT_TYPE VARCHAR(1),
    AIR_TEMPERATURE_K FLOAT,
    PROCESS_TEMPERATURE_K FLOAT,
    ROTATIONAL_SPEED_RPM NUMBER(10, 0),
    TORQUE_NM FLOAT,
    TOOL_WEAR_MIN NUMBER(10, 0),
    MACHINE_FAILURE NUMBER(1, 0),
    TWF NUMBER(1, 0),
    HDF NUMBER(1, 0),
    PWF NUMBER(1, 0),
    OSF NUMBER(1, 0),
    RNF NUMBER(1, 0)
);

