CREATE DATABASE IF NOT EXISTS OAD_DEMO;
CREATE SCHEMA IF NOT EXISTS OAD_DEMO.PUBLIC;

CREATE TABLE IF NOT EXISTS OAD_DEMO.PUBLIC.PRODUCTION_EVENTS (
    EVENT_ID NUMBER(38, 0) NOT NULL,
    EVENT_TS TIMESTAMP_NTZ NOT NULL,
    LINE_ID VARCHAR(16) NOT NULL,
    UNITS_PRODUCED NUMBER(10, 0) NOT NULL,
    UNITS_DEFECTIVE NUMBER(10, 0) NOT NULL
);

-- In Snowsight, load data/production_events.csv into this table with the header row enabled.

