CREATE DATABASE IF NOT EXISTS OAD_DEMO;
CREATE SCHEMA IF NOT EXISTS OAD_DEMO.PUBLIC;

CREATE OR REPLACE TABLE OAD_DEMO.PUBLIC.PRODUCTION_EVENTS (
    EVENT_ID NUMBER(38, 0) NOT NULL,
    EVENT_TS TIMESTAMP_NTZ NOT NULL,
    LINE_ID VARCHAR(16) NOT NULL,
    UNITS_PRODUCED NUMBER(10, 0) NOT NULL,
    UNITS_DEFECTIVE NUMBER(10, 0) NOT NULL
);

-- Generate the same five million deterministic readings as db/init/002_seed.sql.
INSERT INTO OAD_DEMO.PUBLIC.PRODUCTION_EVENTS
    (EVENT_ID, EVENT_TS, LINE_ID, UNITS_PRODUCED, UNITS_DEFECTIVE)
WITH generated AS (
    SELECT SEQ4() + 1 AS EVENT_ID
    FROM TABLE(GENERATOR(ROWCOUNT => 5000000))
), base AS (
    SELECT
        EVENT_ID,
        MOD(EVENT_ID - 1, 4) + 1 AS LINE_NUMBER,
        FLOOR(((EVENT_ID - 1) * 6) / 604800) AS WEEK_NUMBER,
        DATEADD(SECOND, (EVENT_ID - 1) * 6, '2025-01-06 06:00:00'::TIMESTAMP_NTZ) AS EVENT_TS,
        'LINE-' || LPAD(TO_VARCHAR(MOD(EVENT_ID - 1, 4) + 1), 2, '0') AS LINE_ID,
        75 + (MOD(EVENT_ID - 1, 4) + 1) * 15 + MOD(EVENT_ID * 48271, 51) AS BASE_PRODUCTION,
        CASE MOD(EVENT_ID - 1, 4) + 1
            WHEN 1 THEN 0.012
            WHEN 2 THEN 0.018
            WHEN 3 THEN 0.030
            ELSE 0.015
        END
          + MOD(EVENT_ID * 40699, 900) / 100000.0
          + MOD(FLOOR(((EVENT_ID - 1) * 6) / 604800) * 13 + (MOD(EVENT_ID - 1, 4) + 1), 5) / 1000.0 AS DEFECT_RATE
    FROM generated
), scored AS (
    SELECT *, ROUND(BASE_PRODUCTION * (0.88 + MOD(WEEK_NUMBER * 7, 25) / 100.0)) AS UNITS_PRODUCED
    FROM base
)
SELECT EVENT_ID, EVENT_TS, LINE_ID, UNITS_PRODUCED,
       ROUND(UNITS_PRODUCED * DEFECT_RATE)::NUMBER(10, 0)
FROM scored;
