-- The source table should contain the original 10,000 UCI records.
-- Repeats unchanged source observations 500 times for a 5M-row analytical
-- workload. These repeats are benchmark padding, not additional observations.
TRUNCATE TABLE OAD_DEMO.PUBLIC.AI4I_READINGS;
INSERT INTO OAD_DEMO.PUBLIC.AI4I_READINGS
    (READING_ID, REPETITION_NUMBER, UDI, PRODUCT_ID, PRODUCT_TYPE,
     AIR_TEMPERATURE_K, PROCESS_TEMPERATURE_K, ROTATIONAL_SPEED_RPM,
     TORQUE_NM, TOOL_WEAR_MIN, MACHINE_FAILURE, TWF, HDF, PWF, OSF, RNF)
SELECT
    (REPETITION_NUMBER - 1) * 10000 + SOURCE.UDI,
    REPETITION_NUMBER,
    SOURCE.UDI,
    SOURCE.PRODUCT_ID,
    SOURCE.PRODUCT_TYPE,
    SOURCE.AIR_TEMPERATURE_K,
    SOURCE.PROCESS_TEMPERATURE_K,
    SOURCE.ROTATIONAL_SPEED_RPM,
    SOURCE.TORQUE_NM,
    SOURCE.TOOL_WEAR_MIN,
    SOURCE.MACHINE_FAILURE,
    SOURCE.TWF,
    SOURCE.HDF,
    SOURCE.PWF,
    SOURCE.OSF,
    SOURCE.RNF
FROM OAD_DEMO.PUBLIC.AI4I_SOURCE AS SOURCE
CROSS JOIN (
    SELECT SEQ4() + 1 AS REPETITION_NUMBER
    FROM TABLE(GENERATOR(ROWCOUNT => 500))
) AS REPETITIONS;
