-- Run after 001_setup.sql and loading AI4I_SOURCE, with its database/schema selected.
-- Only the first 2,500 original records are used. AI4I_READINGS is excluded.
-- 2,000 training rows: IDs 1..2500 except every fifth row.
-- 500 evaluation rows: every fifth row, never included in training.

CREATE VIEW IF NOT EXISTS AI4I_FAILURE_TRAINING AS
SELECT PRODUCT_TYPE, AIR_TEMPERATURE_K, PROCESS_TEMPERATURE_K,
       ROTATIONAL_SPEED_RPM, TORQUE_NM, TOOL_WEAR_MIN,
       MACHINE_FAILURE = 1 AS MACHINE_FAILURE
FROM AI4I_SOURCE
WHERE UDI <= 2500 AND MOD(UDI, 5) <> 0;

-- Reuses the trained model on subsequent runs.
CREATE SNOWFLAKE.ML.CLASSIFICATION IF NOT EXISTS AI4I_FAILURE_MODEL (
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'AI4I_FAILURE_TRAINING'),
    TARGET_COLNAME => 'MACHINE_FAILURE',
    CONFIG_OBJECT => {'evaluate': FALSE}
);

WITH SCORED AS (
    SELECT PRODUCT_TYPE,
           MACHINE_FAILURE = 1 AS ACTUAL_FAILURE,
           AI4I_FAILURE_MODEL!PREDICT(INPUT_DATA => {
               'PRODUCT_TYPE': PRODUCT_TYPE,
               'AIR_TEMPERATURE_K': AIR_TEMPERATURE_K,
               'PROCESS_TEMPERATURE_K': PROCESS_TEMPERATURE_K,
               'ROTATIONAL_SPEED_RPM': ROTATIONAL_SPEED_RPM,
               'TORQUE_NM': TORQUE_NM,
               'TOOL_WEAR_MIN': TOOL_WEAR_MIN
           }) AS PREDICTION
    FROM AI4I_SOURCE
    WHERE UDI <= 2500 AND MOD(UDI, 5) = 0
), CLASSIFIED AS (
    SELECT PRODUCT_TYPE,
           ACTUAL_FAILURE,
           PREDICTION:"class"::BOOLEAN AS PREDICTED_FAILURE,
           PREDICTION:"probability":"True"::FLOAT AS FAILURE_PROBABILITY
    FROM SCORED
)
SELECT PRODUCT_TYPE,
       COUNT(*) AS TEST_ROWS,
       SUM(IFF(ACTUAL_FAILURE, 1, 0)) AS ACTUAL_FAILURES,
       SUM(IFF(PREDICTED_FAILURE, 1, 0)) AS PREDICTED_FAILURES,
       SUM(IFF(ACTUAL_FAILURE = PREDICTED_FAILURE, 1, 0)) AS CORRECT_PREDICTIONS,
       SUM(IFF(ACTUAL_FAILURE AND PREDICTED_FAILURE, 1, 0)) AS TRUE_POSITIVES,
       SUM(IFF(PREDICTED_FAILURE, 1, 0)) AS PREDICTED_POSITIVES,
       AVG(FAILURE_PROBABILITY) * 100 AS AVG_PREDICTED_RISK_PCT
FROM CLASSIFIED
GROUP BY PRODUCT_TYPE
ORDER BY CASE PRODUCT_TYPE WHEN 'L' THEN 1 WHEN 'M' THEN 2 WHEN 'H' THEN 3 ELSE 4 END;
